name: machine-learning-2022.10
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=h93e1e8c_3
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39hb9d737c_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alembic=1.8.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow-cpp=9.0.0=py39hfd629c7_2_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - asttokens=2.1.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hecaee15_4
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py39hb9d737c_1
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py39h2ae25f5_1
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotli-python=1.0.9=py39h5a03fae_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1014
  - catalogue=2.0.8=py39hf3d152e_1
  - catboost=1.1.1=py39hf3d152e_1
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_2
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - chart-studio=1.1.0=pyh9f0ad1d_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - cmake=3.24.3=h816a3e0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - colorlover=0.3.0=py_0
  - confection=0.0.3=py39hcca971b_1
  - configparser=5.3.0=pyhd8ed1ab_0
  - confuse=2.0.0=pyhd8ed1ab_0
  - contourpy=1.0.6=py39hf939315_0
  - cryptography=38.0.2=py39hd97740a_2
  - cubinlinker=0.2.0=py39h11215e4_1
  - cucim=22.10.00=cuda_11_py39_ga65daf5_0
  - cuda-python=11.7.0=py39h3fd9d12_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cudf=22.10.00=cuda_11_py39_g8ffe375d85_0
  - cudf_kafka=22.10.00=py39_g8ffe375d85_0
  - cudnn=8.4.1.50=hed8a83a_0
  - cufflinks-py=0.17.3=py_0
  - cuml=22.10.00=cuda11_py39_g963d46299_0
  - cupy=11.2.0=py39hc3c280e_0
  - curl=7.86.0=h7bff187_1
  - cusignal=22.10.01=py39_g87393e3_0
  - cuspatial=22.10.00=py39_g4e13a37_0
  - custreamz=22.10.00=py39_g8ffe375d85_0
  - cuxfilter=22.10.00=py39_gb75d9a5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.7=py39h5a03fae_1
  - cyrus-sasl=2.1.27=h230043b_5
  - cython-blis=0.7.8=py39hd257fcd_0
  - cytoolz=0.12.0=py39hb9d737c_1
  - dash=2.6.2=pyhd8ed1ab_0
  - dask=2022.9.2=pyhd8ed1ab_0
  - dask-core=2022.9.2=pyhd8ed1ab_0
  - dask-cuda=22.10.00=py39_g382e519_0
  - dask-cudf=22.10.00=cuda_11_py39_g8ffe375d85_0
  - dask-labextension=6.0.0=pyhd8ed1ab_0
  - dask-sql=2022.10.1=py39hbf5dedb_1
  - databricks-cli=0.17.3=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datashader=0.13.1a=py_0
  - datashape=0.5.4=py_1
  - datefinder=0.7.3=pyhd8ed1ab_0
  - debugpy=1.6.3=py39h5a03fae_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2022.9.2=pyhd8ed1ab_0
  - dlpack=0.5=h9c3ff4c_0
  - docker-py=6.0.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - faiss-proc=1.0.0=cuda
  - fastapi=0.85.2=pyhd8ed1ab_0
  - fastavro=1.7.0=py39hb9d737c_0
  - fastrlock=0.8=py39h5a03fae_3
  - fftw=3.3.10=nompi_hf0379b8_105
  - fiona=1.8.21=py39h54775ec_2
  - flask=2.2.2=pyhd8ed1ab_0
  - flask-compress=1.13=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.13.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39hb9d737c_1
  - freetype=2.12.1=hca18f0e_0
  - freexl=1.0.6=h166bdaf_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.1=py39hb9d737c_1
  - fsspec=2022.10.0=pyhd8ed1ab_0
  - funcy=1.17=pyhd8ed1ab_0
  - future=0.18.2=pyhd8ed1ab_6
  - gast=0.4.0=pyh9f0ad1d_0
  - gdal=3.5.1=py39haa391fb_4
  - gdk-pixbuf=2.42.8=h433bba3_0
  - gensim=4.2.0=py39h1832856_0
  - geopandas=0.12.1=pyhd8ed1ab_0
  - geopandas-base=0.12.1=pyha770c72_0
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_3
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gh=2.18.1=ha8f183a_0
  - giflib=5.2.1=h36c2ea0_2
  - git=2.38.1=pl5321h5fbbf19_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.29=pyhd8ed1ab_0
  - glib=2.74.1=h6239696_0
  - glib-tools=2.74.1=h6239696_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphistry=0.28.5=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=6.0.1=h5abf519_0
  - greenlet=1.1.3.post0=py39h5a03fae_0
  - grpc-cpp=1.46.4=h6fc47f4_3
  - grpcio=1.46.4=py39h4587e31_3
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - gunicorn=20.1.0=py39hf3d152e_3
  - h11=0.14.0=pyhd8ed1ab_0
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - harfbuzz=5.3.0=h418a68e_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h2386368_100
  - heapdict=1.0.1=py_0
  - holoviews=1.14.6=pyhd8ed1ab_0
  - htmlmin=0.1.12=py_1
  - hvplot=0.8.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py39h2ae25f5_6
  - imagehash=4.3.1=pyhd8ed1ab_0
  - imageio=2.22.0=pyhfa7a67d_0
  - imbalanced-learn=0.9.1=pyhd8ed1ab_1
  - importlib-metadata=5.0.0=pyha770c72_1
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - ipycytoscape=1.3.3=pyhd8ed1ab_1
  - ipykernel=6.17.0=pyh210e3f2_0
  - ipython=8.6.0=pyh41d4057_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.0=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyhc268e32_0
  - jupyter-server-proxy=3.2.2=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39hf3d152e_1
  - jupyter_server=1.21.0=pyhd8ed1ab_0
  - jupyterlab=3.5.0=pyhd8ed1ab_0
  - jupyterlab-git=0.39.3=pyhd8ed1ab_0
  - jupyterlab-nvdashboard=0.7.0=py_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.16.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kealib=1.4.15=ha7026e8_1
  - keras=2.9.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - kmodes=0.12.2=pyhd8ed1ab_0
  - krb5=1.19.3=h3790be6_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20211102.0=cxx17_h48a1fff_3
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcucim=22.10.00=cuda11_ga65daf5_0
  - libcudf=22.10.00=cuda11_g8ffe375d85_0
  - libcudf_kafka=22.10.00=g8ffe375d85_0
  - libcugraph=22.10.00=cuda11_gfad6af4e_2
  - libcugraph_etl=22.10.00=cuda11_gfad6af4e_2
  - libcugraphops=22.10.00=cuda11_g4257014_0
  - libcuml=22.10.00=cuda11_g963d46299_0
  - libcumlprims=22.10.00=cuda11_gfdb85e0_0
  - libcurl=7.86.0=h7bff187_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcuspatial=22.10.00=cuda11_g4e13a37_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libfaiss=1.7.0=cuda112h5bea7ad_8_cuda
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h695aa2c_1
  - libgdal=3.5.1=h75ea5e2_4
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h7a41b64_0
  - libgoogle-cloud=1.40.2=hefc27d0_0
  - libgpg-error=1.45=hc0c96e0_0
  - libgsasl=1.10.0=h5b4c23d_0
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=hd77ab85_1
  - libprotobuf=3.20.1=h6239696_4
  - libraft-distance=22.10.00=cuda11_g31ae597_0
  - libraft-headers=22.10.00=cuda11_g31ae597_0
  - libraft-nn=22.10.00=cuda11_g31ae597_0
  - librdkafka=1.7.0=hc49e61c_1
  - librmm=22.10.00=cuda11_g9d5a8c37_0
  - librsvg=2.54.4=h7abd40a_0
  - librttopo=1.1.0=hf730bdb_11
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=hd36657c_19
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.4.0=h55922b4_4
  - libtool=2.4.6=h9c3ff4c_1008
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.6.2dev.rapidsai22.10=cuda_11_1
  - libxml2=2.10.3=h7463322_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=h166bdaf_4
  - lightgbm=3.3.3=py39h5a03fae_1
  - llvm-openmp=14.0.4=he0ac6c6_0
  - llvmlite=0.39.1=py39h7d9a04d_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.0.2=py39h029007f_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=hc72dce7_4
  - mako=1.2.3=pyhd8ed1ab_0
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_2
  - matplotlib-base=3.6.1=py39hf9fd14e_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - missingno=0.4.2=py_1
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-include=2022.1.0=h84fe81f_915
  - mlflow=1.30.0=py39ha39b057_0
  - mlxtend=0.21.0=pyhd8ed1ab_0
  - mpfr=4.1.0=h9202a9a_1
  - msgpack-python=1.0.4=py39hf939315_1
  - multidict=6.0.2=py39hb9d737c_2
  - multimethod=1.4=py_0
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.9=py39h5a03fae_1
  - nbclassic=0.4.5=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.3=pyhd8ed1ab_0
  - nbconvert-core=7.2.3=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.3=pyhd8ed1ab_0
  - nbdime=3.1.1=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - ninja=1.11.0=h924138e_0
  - nltk=3.6.7=pyhd8ed1ab_0
  - nodejs=18.11.0=h96d913c_0
  - noise=1.2.2=py39hb9d737c_1004
  - nomkl=3.0=0
  - notebook=6.5.1=pyha770c72_0
  - notebook-shim=0.2.0=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numba=0.56.3=py39h61ddf18_0
  - numexpr=2.8.3=py39hf625f34_101
  - numpy=1.23.4=py39h3d75532_1
  - nvtx=0.2.3=py39hb9d737c_2
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1s=h166bdaf_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.7.6=h6c59b99_0
  - packaging=21.3=pyhd8ed1ab_0
  - palettable=3.3.0=py_0
  - pandas=1.5.1=py39h4661b88_1
  - pandas-profiling=3.0.0=pyhd8ed1ab_0
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.12.7=pyhd8ed1ab_0
  - pango=1.50.11=h382ae3d_0
  - param=1.12.2=pyh6c4a22f_0
  - paramiko=2.11.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pathy=0.6.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - phik=0.12.2=py39ha791e8c_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hae2aec6_1
  - pip=22.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plotly=5.11.0=pyhd8ed1ab_0
  - poppler=22.04.0=h1434ded_1
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=hdeef612_1
  - preshed=3.0.8=py39h5a03fae_1
  - proj=9.0.1=h93bde94_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.20.3=pyhd8ed1ab_0
  - promise=2.3=py39hf3d152e_7
  - prompt-toolkit=3.0.31=pyha770c72_0
  - protobuf=3.20.1=py39h5a03fae_0
  - psutil=5.9.3=py39hb9d737c_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptxcompiler=0.7.0=py39h1eff087_2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.6.2dev.rapidsai22.10=cuda_11_py39_1
  - pyarrow=9.0.0=py39h58137f1_2_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycaret=2.2.3=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydantic=1.10.2=py39hb9d737c_1
  - pydeck=0.5.0=pyh9f0ad1d_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pyee=8.1.0=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyldavis=3.3.1=pyhd8ed1ab_0
  - pylibcugraph=22.10.00=cuda11_py39_gfad6af4e_2
  - pylibraft=22.10.00=cuda11_py39_g31ae597_0
  - pynacl=1.5.0=py39hb9d737c_2
  - pynndescent=0.5.8=pyh1a96a4e_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyod=1.0.6=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyppeteer=1.0.2=pyhd8ed1ab_0
  - pyproj=3.4.0=py39hdcf6798_0
  - pyrsistent=0.19.1=py39hb9d737c_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=h9a8a25e_0_cpython
  - python-confluent-kafka=1.7.0=py39h3811e60_2
  - python-cufflinks=0.17.3=py_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python-graphviz=0.20.1=pyh22cad53_0
  - python-tzdata=2022.5=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=cuda112py39ha0cca9b_200
  - pytorch-lightning=1.6.5=pyhd8ed1ab_0
  - pytz=2022.5=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py39hf3d152e_3
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyviz_comms=2.2.1=pyhd8ed1ab_1
  - pywavelets=1.3.0=py39h2ae25f5_2
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=24.0.1=py39headdf64_1
  - querystring_parser=1.2.4=py_0
  - raft-dask=22.10.00=cuda11_py39_g31ae597_0
  - rapids=22.10.00=cuda11_py39_gdccf15b_105
  - rapids-xgboost=22.10.00=cuda11_py39_gdccf15b_105
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - regex=2022.10.31=py39hb9d737c_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - retrying=1.3.3=py_2
  - rhash=1.4.3=h166bdaf_0
  - rmm=22.10.00=cuda11_py39_g9d5a8c37_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.0.1=py39hb102c33_1
  - s2n=1.0.10=h9b69904_0
  - scikit-image=0.19.3=py39h4661b88_2
  - scikit-learn=1.1.3=py39hd5c8da3_1
  - scipy=1.9.3=py39hddc5342_1
  - seaborn=0.12.0=hd8ed1ab_0
  - seaborn-base=0.12.0=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentry-sdk=1.10.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=59.5.0=py39hf3d152e_0
  - shapely=1.8.5=py39h5b5020f_1
  - shellingham=1.5.0=pyhd8ed1ab_0
  - shortuuid=1.0.9=pyha770c72_1
  - simpervisor=0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spacy=3.4.2=py39h7c9e3ff_0
  - spacy-legacy=3.0.10=pyhd8ed1ab_0
  - spacy-loggers=1.0.3=pyhd8ed1ab_0
  - spdlog=1.8.5=h4bd325d_1
  - spectate=1.0.1=pyhd8ed1ab_0
  - sqlalchemy=1.4.42=py39hb9d737c_1
  - sqlite=3.39.4=h4ff8645_0
  - sqlparse=0.4.3=pyhd8ed1ab_0
  - squarify=0.4.3=py_0
  - srsly=2.4.5=py39h5a03fae_1
  - stack_data=0.6.0=pyhd8ed1ab_0
  - starlette=0.20.4=pyhd8ed1ab_1
  - statsmodels=0.13.4=py39h2ae25f5_1
  - streamz=0.6.4=pyh6c4a22f_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tangled-up-in-unicode=0.2.0=pyhd8ed1ab_0
  - tbb=2021.6.0=h924138e_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.1.0=pyhd8ed1ab_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39hd97740a_3
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.9.1=cuda112py39h01bd6f0_0
  - tensorflow-base=2.9.1=cuda112py39h81abfd3_0
  - tensorflow-estimator=2.9.1=cuda112py39hd320b7a_0
  - termcolor=2.1.0=pyhd8ed1ab_0
  - terminado=0.17.0=pyh41d4057_0
  - textblob=0.15.3=py_0
  - thinc=8.1.5=py39h7c9e3ff_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2020.6.3=py_0
  - tiledb=2.11.3=h1e4a385_1
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchmetrics=0.10.1=pyhd8ed1ab_0
  - torchvision=0.13.0=cuda112py39hd2c45b6_0
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.5.0=pyhd8ed1ab_0
  - treelite=3.0.0=py39hc7ff369_1
  - typer=0.4.2=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzcode=2022e=h166bdaf_0
  - tzdata=2022f=h191b570_0
  - tzlocal=4.2=py39hf3d152e_2
  - ucx=1.13.1=h538f049_0
  - ucx-proc=1.0.0=gpu
  - ucx-py=0.28.00=py39_g8292636_0
  - umap-learn=0.5.3=py39hf3d152e_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - uvicorn=0.19.0=py39hf3d152e_0
  - visions=0.7.1=pyhd8ed1ab_0
  - wandb=0.13.4=pyhd8ed1ab_0
  - wasabi=0.10.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - websockets=10.4=py39hb9d737c_1
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - wordcloud=1.8.2.2=py39hb9d737c_1
  - wrapt=1.14.1=py39hb9d737c_1
  - xarray=2022.10.0=pyhd8ed1ab_0
  - xarray-spatial=0.3.5=pyhd8ed1ab_0
  - xerces-c=3.2.4=h55805fa_1
  - xeus=2.4.1=h70bab47_0
  - xeus-python=0.14.3=py39h800c839_0
  - xeus-python-shell=0.5.0=pyhd8ed1ab_0
  - xeus-python-shell-raw=0.5.0=pyhd8ed1ab_0
  - xgboost=1.6.2dev.rapidsai22.10=cuda_11_py39_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.1=py39hb9d737c_0
  - yellowbrick=1.5=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
    - cugraph==22.10.0+2.gfad6af4e.dirty
    - treelite-runtime==3.0.0
